export const actionTypes = {
  FETCH_CITY_AND_STATE: "FETCH_CITY_AND_STATE",
  SET_EMAIL: "SET_EMAIL",
  SET_CELL: "SET_CELL",
  SET_NAME_FIRST: "SET_NAME_FIRST",
  SET_NAME_LAST: "SET_NAME_LAST",
  SET_NAME_TITLE: "SET_NAME_TITLE",
  SET_LOCATION_STREET: "SET_LOCATION_STREET",
  SET_LOCATION_CITY: "SET_LOCATION_CITY",
  SET_LOCATION_STATE: "SET_LOCATION_STATE",
  SET_LOCATION_POSTCODE: "SET_LOCATION_POSTCODE",
};